// Deploys the pilot service to a standalone Cloudflare Worker.
//
//   npm run deploy:pilot
//
// Credentials come only from the gitignored, owner-only .env.pilot file in this
// directory (see .env.pilot.example). Global Cloudflare logins are never used:
// the script refuses to run without CLOUDFLARE_API_TOKEN in that file.
// Deployment identifiers are kept in the gitignored .pilot/ and
// wrangler.pilot.jsonc, never in the repository.
import { execFileSync, spawnSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { existsSync, readFileSync, statSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");

const envFile = join(root, ".env.pilot");

const stateDir = join(root, ".pilot");

const statePath = join(stateDir, "state.json");

const configPath = join(root, "wrangler.pilot.jsonc");

const wrangler = join(root, "node_modules", ".bin", "wrangler");

const credentials = readCredentials();

const workerName =
  credentials.PILOT_WORKER_NAME || "expanso-fleet-chatgpt-pilot";

const state = existsSync(statePath)
  ? JSON.parse(readFileSync(statePath, "utf8"))
  : {};

// Only what wrangler needs; never inherit other Cloudflare settings.
const childEnv = {
  PATH: process.env.PATH,
  HOME: process.env.HOME,
  CLOUDFLARE_API_TOKEN: credentials.CLOUDFLARE_API_TOKEN,
  CLOUDFLARE_ACCOUNT_ID: credentials.CLOUDFLARE_ACCOUNT_ID,
  WRANGLER_SEND_METRICS: "false",
  CI: "true",
};

run("npm", ["run", "build"], { env: process.env });

if (!state.kvId) {
  state.kvId = createKvNamespace(`${workerName}-oauth`);
  await saveState();
}

await writeConfig();

state.url = deploy();

await saveState();

if (!state.publicBaseUrlSet) {
  // The first deploy learns the workers.dev URL; pin it as the OAuth issuer.
  await writeConfig();
  deploy();
  state.publicBaseUrlSet = true;
  await saveState();
}

if (!state.encryptionKeySet) {
  // Generated here and handed straight to Cloudflare; never printed or stored.
  const key = randomBytes(32).toString("base64");

  run(wrangler, ["secret", "put", "LINK_ENCRYPTION_KEY", "-c", configPath], {
    env: childEnv,
    input: key,
  });

  state.encryptionKeySet = true;
  await saveState();
}

console.log(`\nPilot MCP server: ${state.url}/mcp`);

console.log("Build the plugin with: npm run build:plugin -- --install");

function readCredentials() {
  if (!existsSync(envFile)) {
    fail(`Missing ${envFile}. Copy .env.pilot.example and fill it in.`);
  }

  if ((statSync(envFile).mode & 0o077) !== 0) {
    fail(`${envFile} must be readable only by you (mode 600).`);
  }

  const values = {};

  for (const line of readFileSync(envFile, "utf8").split("\n")) {
    const match = /^\s*([A-Z_][A-Z0-9_]*)\s*=\s*(.*?)\s*$/.exec(line);

    if (match) values[match[1]] = match[2].replace(/^["']|["']$/g, "");
  }

  for (const name of ["CLOUDFLARE_API_TOKEN", "CLOUDFLARE_ACCOUNT_ID"]) {
    if (!values[name]) fail(`${name} is missing from ${envFile}.`);
  }

  return values;
}

function createKvNamespace(title) {
  const listed = capture(wrangler, ["kv", "namespace", "list"]);
  const existing = JSON.parse(listed).find((item) => item.title === title);

  if (existing) return existing.id;

  const created = capture(wrangler, ["kv", "namespace", "create", title]);
  const id = /"?id"?\s*[:=]\s*"([0-9a-f]{32})"/.exec(created)?.[1];

  if (!id) fail("Could not read the new KV namespace ID from wrangler.");

  return id;
}

async function writeConfig() {
  const config = {
    name: workerName,
    main: "dist/worker/worker.js",
    no_bundle: true,
    compatibility_date: "2026-09-01",
    compatibility_flags: ["nodejs_compat"],
    workers_dev: true,
    kv_namespaces: [{ binding: "OAUTH_KV", id: state.kvId }],
    vars: state.url ? { PUBLIC_BASE_URL: state.url } : {},
  };

  await writeFile(
    configPath,
    `// Generated by scripts/deploy-pilot.mjs. Gitignored.\n${JSON.stringify(config, null, 2)}\n`,
  );
}

function deploy() {
  const output = capture(wrangler, ["deploy", "-c", configPath]);
  const url = /https:\/\/[a-z0-9.-]+\.workers\.dev/.exec(output)?.[0];

  if (!url) fail("The deploy finished but no workers.dev URL was reported.");

  return url;
}

async function saveState() {
  await mkdir(stateDir, { recursive: true });
  await writeFile(statePath, `${JSON.stringify(state, null, 2)}\n`);
}

function capture(command, args) {
  return execFileSync(command, args, {
    cwd: root,
    env: childEnv,
    encoding: "utf8",
    stdio: ["ignore", "pipe", "inherit"],
  });
}

function run(command, args, options) {
  const result = spawnSync(command, args, {
    cwd: root,
    stdio: [
      options.input === undefined ? "inherit" : "pipe",
      "inherit",
      "inherit",
    ],
    input: options.input,
    env: options.env,
  });

  if (result.status !== 0) fail(`${command} ${args[0]} failed.`);
}

function fail(message) {
  console.error(message);
  process.exit(1);
}
