// Embeds the built Fleet app and the plugin icon into a module the Worker
// imports, so the deployed Worker needs no asset bindings.
import { mkdir, readFile, writeFile } from "node:fs/promises";

const root = new URL("..", import.meta.url);

const html = await readFile(new URL("app/dist/index.html", root), "utf8");

const icon = await readFile(new URL("plugin/assets/icon.svg", root), "utf8");

await mkdir(new URL("src/generated/", root), { recursive: true });

await writeFile(
  new URL("src/generated/assets.ts", root),
  `// Generated by scripts/embed-app.mjs. Do not edit.\n` +
    `export const FLEET_APP_HTML = ${JSON.stringify(html)};\n` +
    `export const ICON_SVG = ${JSON.stringify(icon.trim())};\n`,
);

console.log(`Embedded Fleet app (${html.length} bytes) and icon.`);
